### ISSUE TITLE
matrix with float

### ISSUE THREAD

**Issue by thewoz** [soimy/munkres-opencv#3]
Hi,

I love your work!
I would like to know if you have in mind to release a version that permit the use of float matrix.

thanks in advance

**Comment by Gluttton** [comment]
@thewoz , how about using https://github.com/Gluttton/munkres-cpp/blob/master/src/munkres-cpp/munkres.h with https://github.com/Gluttton/munkres-cpp/blob/master/src/munkres-cpp/adapters/matrix_opencv.h . The similar example: https://github.com/Gluttton/munkres-cpp/blob/master/examples/example_03.cpp .

**Comment by thewoz** [comment]
Hi  Gluttton!!

The links dosen't work...

:(

**Comment by Gluttton** [comment]
@thewoz , yep.

Please, just replace every `github` on `gitlab` in every link.

**Comment by Gluttton** [comment]
@thewoz , here are correct links: https://gitlab.com/Gluttton/munkres-cpp/blob/master/src/munkres-cpp/munkres.h with https://gitlab.com/Gluttton/munkres-cpp/blob/master/src/munkres-cpp/adapters/matrix_opencv.h, example of usage: https://gitlab.com/Gluttton/munkres-cpp/blob/master/examples/example_03.cpp .

**Comment by thewoz** [comment]
:)
